# Generated by Django 4.2.1 on 2023-06-13 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_backgroundcolor_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.DeleteModel(
            name='Color',
        ),
    ]
